### ISSUE TITLE
АВТОР ГОВНОЕД АНИМЭШНЫЙ

### ISSUE THREAD

**Issue by edwardfreedom** [d0kur0/instbot#13]
ЧТО ЛОШАРА ГОВНОЕДНАЯ, НЕ ПОТЯНУЛ НА ЗАПРОСАХ СДЕЛАТЬ, А СДЕЛАЛ КАК ШКОЛОВЫБЛЯДОК НА БРАУЗЕРЕ? ПХПХПХПХ ИДИ ГОВНО ЖРИ ТВАРЬ

**Comment by edwardfreedom** [comment]
ПС, ЭТА ДУРА РАБОТАЕТ НА ФОРУМЕ КРУГЛОСУТОЧНО ЗА 100 РУБ В ЧАС ПХАХАХ ОБОССЫТЕ ЭТОМУ ЧМОШНИКУ ЕГО МОРДУ

**Comment by d0kur0** [comment]
Ты понимаешь, что выглядишь как человек, который лежит на спине и ссыт себе на лицо? Лол.
Сгорел с деактивации твоего аккаунта? Хех.

Иди коз паси, поросенок Петр.

**Comment by edwardfreedom** [comment]
лол забанили на месяц, а анимэшник уже горит пхахах, говорит про коз козлов васек, иди какашки жри

**Comment by d0kur0** [comment]
@edwardfreedom сасеш
