### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Strannik74** [d0kur0/instbot#3]
Добрый день!
Отличная прога, функционал замечательный. Работал до вчерашнего дня. 
Программа авторизуется, отклоняет всплывющие окна, дальше на хештег не переходит, и отключается. Проверено на windows и linux.

![inst_01](https://user-images.githubusercontent.com/31668854/87246732-9d203d00-c468-11ea-8316-7e7e3f337a0e.jpg)

**Comment by d0kur0** [comment]
Привет, Инстаграм обновлялся и сломал селектор, проблема исправлена, скачайте обновленную версию.
